language: php
php:
- 5.5
script: phpunit Test.php
notifications:
  webhooks: $WEBHOOK_URL
env:
  global:
    secure: ghxh3pgYP+DKAl/CBhKlEg1Iqpm+9q4XKDMwRmm+LGqBkd7CHuCu3UrRZTCB3Sq6niOLPJefDxwvDfkNPpdwPS5h4DtEmum4jCDcYoyqlNdxifZ6QgRea8Vaxp7zceM0sVyQCEaDq3hntNzZPZDP8XdBkSfPwwSkK2pttp/7TGKQw3eApHf7HxCBXOzg0+rwNZYd/PWIo23+pmtacr04SGrTgJALoHo4dvIAvWuvBEnoDjRc8b1TDuSgfdjeKDPzN1oPzER9CiDM1ZYJCntwfSMmiVGt5RpBzP1GJTD9SOxCBZ3NpWikrmnBUIVPPYhBcBUl/0W0E0rpBfoYdoc6/DPSBrTXQigvVTkqArdkT7pFoEZLUky6DbaKmG2uC4KHHSz8PSiIT8FBWd836CNMibjAg5R2ErxG6xWNOdXo0XI8nwFv2HG4J2Wvg9E0QtOE9gua/qFwDy3YV0tgAwi21SbRc2U1rSlHtPR6MO0NCm22xFN8P3tiqQvdYVx+QsR4yL0kQghh4UA3NK3lAFWOF0w2+0BIUJFSKmGGXU00huWg+eoydxqc4980hfFtZsepKmmR+93OPxBqZ0WKLKBqyc5FiwnVwKDOiIHDqGHzRaYib6leLwIuFmylxD+myG25JRVW3EGWys8YIrf9pH0jT+ryyMREpio+va69lwXepJ0=
