language: php
php:
- 5.5
script: phpunit Test.php
notifications:
  webhooks:
    secure: n3X3yXbu/wMwWZeft7y/4CrXKyNU+uchcobgIy9pI27GLZyqSFuWv36nOHIKb3MLNbolUUQRY5PWxQDnHAhmPsIvh5y1Gc8Lf7m3sa4ADypkiUQhdddaO/9iJlUUFxPSAW8j9U290GJEgKzuK0Iag6Pnb0UAikTrFvjqbWPMeutTp/8i3+sPhMiNSgwsD4me0nYVJAk+hazO1Q0tikjm37/yYJu5wxZK5lqxxuqt7H/lUFFnKbusncBTQLKzGCsr/JeyyPPJUZwR+tGD9BigqBkrnqb9w5nZ6BlYbdkNGcmtNjUSfW7FUxcmrEyRX+v+Wev0TfgG+4UJnsfJ7tZ1YPTWCYM6jz8hhZU+4L1mGMw7Na+BrLocUSRAkoCeqMqL5m0zT37bol/xdSIEqUIwBgeF2s9XqwXi6r1q1GqgBRyFLcI0vWjfwe9BzugLqD2pXUHsvJq0HWh+p3vkZaanH8l6cOXOt09i6WvD8La1REWa7GjHTh1ry+CUnB52gh6G0BRbMMWWliV01jmUvDBAFz9QFNa/TmrJ8GAE5pQQXpFGDFEhST8gf6nWw2WWhEdFpvJn60Ka0k8MfSgQUd7pyOhcPeyIsRBrV7e2P/z4MSME5hgni8fvENOJ7rdNEpO4CTRIckAcaECtvqEkNncdzfvKnpqXV+7dZber8VnWQxI=
